#!/usr/bin/env python
"""
Auto-generated reproducible imputation script (self-verifying).

Generated by missingness-auditor. Re-applies the exact imputation plan that was
recommended for `source_data.csv`, fitting all statistics on the
training data only, then checks its own work. No dependency on the auditor package.

Usage:
    python reproduce_imputation.py
"""

import json
import os

import numpy as np
import pandas as pd

# --- Embedded imputation plan -------------------------------------------------
PLAN = json.loads(r"""
{
    "columns": {
        "state": {
            "strategy": "no_imputation_needed",
            "add_missing_indicator": false,
            "reason": "no_missing_values",
            "fit_on": "N/A",
            "missing_rate": 0.0,
            "dtype": "object",
            "cardinality": 15,
            "mechanism_label": "MCAR-compatible",
            "target_association_evidence": null,
            "covariate_association_evidence": [],
            "group_dependency_evidence": null,
            "structural_evidence": null,
            "safety_warning": null,
            "mi_upgrade_recommended": false
        },
        "week": {
            "strategy": "no_imputation_needed",
            "add_missing_indicator": false,
            "reason": "no_missing_values",
            "fit_on": "N/A",
            "missing_rate": 0.0,
            "dtype": "int64",
            "cardinality": 52,
            "mechanism_label": "MCAR-compatible",
            "target_association_evidence": null,
            "covariate_association_evidence": [],
            "group_dependency_evidence": null,
            "structural_evidence": null,
            "safety_warning": null,
            "mi_upgrade_recommended": false
        },
        "population_100k": {
            "strategy": "no_imputation_needed",
            "add_missing_indicator": false,
            "reason": "no_missing_values",
            "fit_on": "N/A",
            "missing_rate": 0.0,
            "dtype": "float64",
            "cardinality": 451,
            "mechanism_label": "MCAR-compatible",
            "target_association_evidence": null,
            "covariate_association_evidence": [],
            "group_dependency_evidence": null,
            "structural_evidence": null,
            "safety_warning": null,
            "mi_upgrade_recommended": false
        },
        "ed_visit_rate": {
            "strategy": "groupwise_numeric_median_plus_indicator",
            "add_missing_indicator": true,
            "reason": "group_dependent_missingness_by_feature='state'",
            "fit_on": "train_only",
            "missing_rate": 0.1449,
            "dtype": "float64",
            "cardinality": 539,
            "mechanism_label": "group-dependent missingness",
            "target_association_evidence": {
                "detected": false,
                "correlation": null
            },
            "covariate_association_evidence": [],
            "group_dependency_evidence": {
                "detected": true,
                "top_categorical_feature": "state",
                "max_missingness_spread": 0.4615,
                "high_missing_groups": {}
            },
            "structural_evidence": null,
            "safety_warning": null,
            "mi_upgrade_recommended": true,
            "group_col": "state"
        },
        "naloxone_admin_rate": {
            "strategy": "time_series_ffill_bfill_plus_indicator",
            "add_missing_indicator": true,
            "reason": "domain='time_series_metric'_temporal_measurement_ffill_preferred_over_median",
            "fit_on": "train_only",
            "missing_rate": 0.1,
            "dtype": "float64",
            "cardinality": 647,
            "mechanism_label": "MCAR-compatible",
            "target_association_evidence": {
                "detected": false,
                "correlation": null
            },
            "covariate_association_evidence": [],
            "group_dependency_evidence": {
                "detected": false
            },
            "structural_evidence": null,
            "safety_warning": "sort_by_time_column_before_applying_ffill_bfill",
            "mi_upgrade_recommended": false
        },
        "subprogram_type": {
            "strategy": "structural_none_token_plus_indicator",
            "add_missing_indicator": true,
            "reason": "structural_absence_categorical_na_encodes_absence",
            "fit_on": "train_only",
            "missing_rate": 0.3333,
            "dtype": "object",
            "cardinality": 3,
            "mechanism_label": "structural absence concern",
            "target_association_evidence": {
                "detected": false,
                "correlation": null
            },
            "covariate_association_evidence": [
                {
                    "feature": "copresent_subrate",
                    "correlation": 0.7262
                },
                {
                    "feature": "naloxone_admin_rate",
                    "correlation": 0.1948
                },
                {
                    "feature": "population_100k",
                    "correlation": 0.1683
                }
            ],
            "group_dependency_evidence": {
                "detected": true,
                "top_categorical_feature": "state",
                "max_missingness_spread": 1.0,
                "high_missing_groups": {
                    "AL": 1.0,
                    "CA": 1.0,
                    "MI": 1.0,
                    "NC": 1.0,
                    "OH": 1.0
                }
            },
            "structural_evidence": {
                "detected": true,
                "pattern": "structural_absence",
                "companion_columns": [
                    "copresent_subrate"
                ]
            },
            "safety_warning": null,
            "mi_upgrade_recommended": true
        },
        "copresent_subrate": {
            "strategy": "no_imputation_needed",
            "add_missing_indicator": false,
            "reason": "no_missing_values",
            "fit_on": "N/A",
            "missing_rate": 0.0,
            "dtype": "float64",
            "cardinality": 380,
            "mechanism_label": "structural absence concern",
            "target_association_evidence": null,
            "covariate_association_evidence": [],
            "group_dependency_evidence": null,
            "structural_evidence": {
                "detected": true,
                "pattern": "structural_absence",
                "companion_columns": [
                    "subprogram_type"
                ]
            },
            "safety_warning": null,
            "mi_upgrade_recommended": false
        }
    },
    "summary": {
        "strategy_counts": {
            "no_imputation_needed": 4,
            "groupwise_numeric_median_plus_indicator": 1,
            "time_series_ffill_bfill_plus_indicator": 1,
            "structural_none_token_plus_indicator": 1
        },
        "columns_needing_missing_indicator": [
            "ed_visit_rate",
            "naloxone_admin_rate",
            "subprogram_type"
        ],
        "n_columns_to_impute": 3,
        "columns_where_full_mi_recommended": [
            "ed_visit_rate",
            "subprogram_type"
        ]
    },
    "leakage_protocol": "All imputation statistics (median, mode, group medians, model parameters) must be fitted on training data only and applied to prediction data."
}
""")

TARGET_COL = None
# Data path is resolved relative to this script so the artifact stays portable.
_HERE = os.path.dirname(os.path.abspath(__file__))
DATA_PATH = os.path.join(_HERE, 'source_data.csv')

# --- Imputation engine (leakage-safe; statistics fitted on training data only) -

def _add_indicator(df, col):
    df[f"{col}_was_missing"] = df[col].isna().astype(int)
    return df


def apply_plan(df_train, plan, df_predict=None):
    """Re-apply an imputation plan. All statistics are fitted on df_train only."""
    df_train = df_train.copy()
    if df_predict is not None:
        df_predict = df_predict.copy()
    drop_cols = []
    for col, entry in plan.get("columns", {}).items():
        strategy = entry["strategy"]
        add_ind = entry.get("add_missing_indicator", False)
        if strategy == "no_imputation_needed":
            continue
        if strategy == "drop_column":
            drop_cols.append(col)
            continue
        if col not in df_train.columns:
            continue
        if add_ind:
            df_train = _add_indicator(df_train, col)
            if df_predict is not None and col in df_predict.columns:
                df_predict = _add_indicator(df_predict, col)

        if strategy in ("groupwise_numeric_median_plus_indicator", "group_median"):
            group_col = entry.get("group_col")
            global_median = df_train[col].median()
            if group_col and group_col in df_train.columns:
                gmap = df_train.groupby(group_col)[col].median().to_dict()
                df_train[col] = df_train[col].fillna(df_train[group_col].map(gmap))
                if df_predict is not None and col in df_predict.columns and group_col in df_predict.columns:
                    df_predict[col] = df_predict[col].fillna(df_predict[group_col].map(gmap))
            df_train[col] = df_train[col].fillna(global_median)
            if df_predict is not None and col in df_predict.columns:
                df_predict[col] = df_predict[col].fillna(global_median)
        elif strategy == "time_series_ffill_bfill_plus_indicator":
            df_train[col] = df_train[col].ffill().bfill()
            fallback = df_train[col].median()
            df_train[col] = df_train[col].fillna(fallback)
            if df_predict is not None and col in df_predict.columns:
                df_predict[col] = df_predict[col].ffill().bfill().fillna(fallback)
        elif strategy in ("categorical_missing_token", "categorical_missing_token_plus_indicator"):
            df_train[col] = df_train[col].fillna("MISSING")
            if df_predict is not None and col in df_predict.columns:
                df_predict[col] = df_predict[col].fillna("MISSING")
        elif strategy == "categorical_mode_plus_indicator":
            mode_vals = df_train[col].mode()
            fill = mode_vals.iloc[0] if len(mode_vals) else "MISSING"
            df_train[col] = df_train[col].fillna(fill)
            if df_predict is not None and col in df_predict.columns:
                df_predict[col] = df_predict[col].fillna(fill)
        elif strategy == "structural_none_token_plus_indicator":
            df_train[col] = df_train[col].fillna("NONE")
            if df_predict is not None and col in df_predict.columns:
                df_predict[col] = df_predict[col].fillna("NONE")
        elif strategy == "structural_zero_plus_indicator":
            df_train[col] = df_train[col].fillna(0)
            if df_predict is not None and col in df_predict.columns:
                df_predict[col] = df_predict[col].fillna(0)
        elif strategy == "structural_none_or_zero":
            import pandas as _pd
            fill = 0 if _pd.api.types.is_numeric_dtype(df_train[col]) else "NONE"
            df_train[col] = df_train[col].fillna(fill)
            if df_predict is not None and col in df_predict.columns:
                df_predict[col] = df_predict[col].fillna(fill)
        else:
            # numeric_median, numeric_median_plus_indicator, and model-based
            # strategies all reduce to a leakage-safe median in this standalone
            # script (the package uses IterativeImputer for the model-based case).
            fill = df_train[col].median()
            df_train[col] = df_train[col].fillna(fill)
            if df_predict is not None and col in df_predict.columns:
                df_predict[col] = df_predict[col].fillna(fill)

    if drop_cols:
        df_train = df_train.drop(columns=drop_cols, errors="ignore")
        if df_predict is not None:
            df_predict = df_predict.drop(columns=drop_cols, errors="ignore")
    if df_predict is not None:
        return df_train, df_predict
    return df_train


def self_verify(df_imputed, plan, target_col, original_target=None):
    """Assert the cleaning honoured its own guarantees."""
    failures = []
    cols = plan.get("columns", {})
    dropped = {c for c, e in cols.items() if e["strategy"] == "drop_column"}
    for col, entry in cols.items():
        if entry["strategy"] in ("no_imputation_needed", "drop_column"):
            continue
        if col in df_imputed.columns and df_imputed[col].isna().any():
            failures.append(f"{col}: {int(df_imputed[col].isna().sum())} nulls remain")
        if entry.get("add_missing_indicator"):
            ind = f"{col}_was_missing"
            if ind in df_imputed.columns:
                uniq = set(df_imputed[ind].dropna().unique())
                if not uniq.issubset({0, 1}):
                    failures.append(f"{ind}: indicator not binary ({uniq})")
    if target_col and original_target is not None and target_col in df_imputed.columns:
        import pandas as _pd
        if not df_imputed[target_col].reset_index(drop=True).equals(
            _pd.Series(original_target).reset_index(drop=True)
        ):
            failures.append(f"target column '{target_col}' was modified")
    for c in dropped:
        if c in df_imputed.columns:
            failures.append(f"drop_column '{c}' still present")
    return failures


# --- Run ----------------------------------------------------------------------
def main():
    if not os.path.exists(DATA_PATH):
        raise SystemExit(f"Original data not found at {DATA_PATH}")
    df = pd.read_csv(DATA_PATH)
    original_target = df[TARGET_COL].copy() if (TARGET_COL and TARGET_COL in df.columns) else None

    imputed = apply_plan(df, PLAN)
    failures = self_verify(imputed, PLAN, TARGET_COL, original_target)

    if failures:
        print("SELF-VERIFICATION FAILED:")
        for f in failures:
            print("  -", f)
        raise SystemExit(1)

    out = os.path.join(_HERE, "reproduced_imputed.csv")
    imputed.to_csv(out, index=False)
    print(f"OK - reproduced cleaned dataset ({len(imputed)} rows, "
          f"{imputed.shape[1]} cols) -> {out}")
    print("Self-verification passed: no residual nulls, target untouched, "
          "indicators binary.")


if __name__ == "__main__":
    main()
